#pragma checksum "q55dyket.nz4" "{ ff1816ec-aa5e-4d10-87f7-6f4963833460}" "e38813938b516fcf140308e1e5b46c15e2075c5e"
// <auto-generated/>
#pragma warning disable 1591
namespace FenixAlliance.ABS.Core.Templating.Dynamic
{
#line hidden
#nullable restore
#line 1 "q55dyket.nz4"
	using System;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "q55dyket.nz4"
	using System.Text;

#line default
#line hidden
#nullable disable
	public class Template : ABM.Data.Access.Services.Templating.Razor.Templates.DynamicComponentBase
	{
#pragma warning disable 1998
		public async override global::System.Threading.Tasks.Task ExecuteAsync()
		{
			WriteLiteral(@"<div class=""wsmenucontainer clearfix"">
	<div class=""overlapblackbg""></div>
	<div class=""header"">
		<div class=""wrapper clearfix bigmegamenu"">
			<div class=""logo clearfix"" style=""display: inline-flex;"">
				<a href=""/"" title=""Logo""><img src=""/images/logos/fenixalliance/FenixAlliance.Dec.Iso.White.Logo.White.h208.png"" style=""max-height:35px; margin-left:5%;margin-top:8%;""");
			BeginWriteAttribute("alt", " alt=\"", 544, "\"", 550, 0);
			EndWriteAttribute();
			WriteLiteral("></a>\n\t\t\t</div>\n\t\t</div>\n\t</div>\n</div>\n");
#nullable restore
#line 15 "q55dyket.nz4"
			Write(Body);

#line default
#line hidden
#nullable disable
			WriteLiteral(@"
<footer class=""footer-area text-white"">
	<div class=""mini-footer"">
		<!--!-->
		<div class=""container"">
			<!--!-->
			<div class=""row"">
				<!--!-->
				<div class=""col-md-12"">
					<!--!-->
					<div class=""copyright-text"">
						<!--!-->
						<p>
							<!--!-->
							© ");
#nullable restore
#line 29 "q55dyket.nz4"
			Write(DateTime.Now.Year);

#line default
#line hidden
#nullable disable
			WriteLiteral(@" 
							<!--!-->
							<a href=""/"" class=""active"">Fenix Alliance SAS.</a>
							<!-- To remove this notice, you need a commercial License for the Alliance Business Suite. Get yours at https://absuite.net -->
							All rights reserved. Powered by
							<a href=""https://absuite.net"" target=""_blank"">Alliance Business Suite</a>.
						</p>
						<!--!-->
					</div>
					<!--!-->
				</div>
				<!--!-->
			</div>
			<!--!-->
		</div>
		<!--!-->
	</div>
</footer>");
		}
#pragma warning restore 1998
	}
}
#pragma warning restore 1591
